### ISSUE TITLE
delete date of birth

### ISSUE THREAD

**Issue by FabiusHaselnuss** [DankDumpster/birthday-bot#1]
How can I delete the date of birth of a user unfortunately I couldn't find it in postgresql

**Comment by DankDumpster** [comment]
Unfortunately its not a feature in the bot because most people don't change birthday. What you could do is running an delete command in the psql shell. 

````sql
DELETE FROM birthdaybot.birthdays WHERE user_id = 123
````

**Comment by FabiusHaselnuss** [comment]
user_id is the discord user id?

**Comment by DankDumpster** [comment]
You can get a user's id by setting your discord to developer mode
More info [here](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)
